### ISSUE TITLE
How to convert .ifc file to .obj/.ply/.png

### ISSUE THREAD

**Issue by saladcat** [cemunds/ifcnet-models#3]
Would you like to share the code with us?

**Comment by cemunds** [comment]
The code is already available under _src/data/make\_*\_data.py_ (with the * being substituted for mvcnn, dgcnn or meshnet). For DGCNN, the script should be straightforward to execute. The MeshNet script has two stages, one to simplify the models and one to convert them to npz. The MVCNN script is a Blender script and you can find instructions on how to execute it [here](https://github.com/WeiTang114/BlenderPhong).

**Comment by saladcat** [comment]
Thank you for your prompt reply

**Comment by cemunds** [comment]
The script to convert to obj is not included here, as I just wrote that on the fly. But I just invoked the [IfcConvert](http://ifcopenshell.org/ifcconvert) console application as a subprocess from a Python script for every IFC file.

**Comment by saladcat** [comment]
> The script to convert to obj is not included here, as I just wrote that on the fly. But I just invoked the [IfcConvert](http://ifcopenshell.org/ifcconvert) console application as a subprocess from a Python script for every IFC file.

oh, I just wanted to ask you and answered, Thankyou
